// Generated by CoffeeScript 1.7.1
var Travis, travis;

if (typeof Travis === "undefined" || Travis === null) {
  Travis = require('../../build/travis');
}

travis = new Travis;

travis.repositories(function(repos) {
  var repo, _i, _len, _results;
  _results = [];
  for (_i = 0, _len = repos.length; _i < _len; _i++) {
    repo = repos[_i];
    _results.push(repo.attributes(function(r) {
      var info;
      info = "repository " + r.slug + ": " + r.lastBuildState;
      if (typeof document !== "undefined" && document !== null) {
        return document.writeln(info + "<br>");
      } else {
        return console.log(info);
      }
    }));
  }
  return _results;
});
